baseURL = 'https://leaimy.github.io/'
languageCode = 'vi-vn'
title = 'Blog Nguyễn Thị Hà'
theme = "ananke"


resourceDir = "../resources"

SectionPagesMenu = "main"
Paginate = 10 
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Nguyễn Thị Hà"
  favicon = ""
  site_logo = ""
  description = "Ha Nguyen Thi personal blog"
  background_color_class = "bg-black"
  recent_posts_number = 3
  body_classes = "avenir bg-near-white"
  post_content_classes = "helvetica"
  show_reading_time = true

[[params.ananke_socials]]
name = "github"
url = "https://github.com/LeAiMy"